### ISSUE TITLE
Json report mode ascii art

### ISSUE THREAD

**Issue by FlorianHeigl** [linkedin/fossor#14]
Hi,

I've just played with the different output modes. Stdout mode has a bit too many decorations for my taste, so I looked at the json mode.
I wonder if you intentionally include the graphs in json mode? Could you tell about how you use them? Are you archiving the json reports?

```
[...removed...]
                              \n \\        -                                                                  |\\                               \n  \\------/ \\----------------------------------------------------------------/  \\------------------------------\nLower value: 0.00 ******************************************************* Mean: 2.69 *** Std Dev: 12.35 ******\nFri May 25 17:30:42 2018                                                              Fri May 25 18:00:01 2018\n"
```

(gotta scroll to the right in the above code block)

**Comment by scallister** [comment]
We don't currently use json internally, but I added json for flexibility. The graphs being included in json mode is an unintended side effect :).

Longterm we're probably going to use the json for outputting cleanly to Slack internally without the table formatting. We also need to add a mode that has less decoration in general.

**Comment by FlorianHeigl** [comment]
Thanks for the explanation, it is good to know it's not intentional but simply happens to be included :)
I'll not try to help with the decorations (too much for me), but hopefully I can make a few plugins.
I later noticed your mail address in the README, so when time's ready I'll write there.

I am _very_ fond of the ideas behind fossor.
