### ISSUE TITLE
dmesg skipped on Ubuntu platform due to binary location 

### ISSUE THREAD

**Issue by jesseward** [linkedin/fossor#2]
The `dmesg` (https://github.com/linkedin/fossor/blob/master/fossor/checks/dmesg.py#L28) plugin references `/usr/bin/dmesg` . file paths will differ between distributions. 
 
```bash

$fossor --debug
...
[Errno 2] No such file or directory: '/usr/bin/dmesg': '/usr/bin/dmesg
...
```
add logic to check common paths bin locations when running plugin

**Comment by lorencarvalho** [comment]
Might I recommend "find_executable" from the distutils module https://github.com/python/cpython/blob/master/Lib/distutils/spawn.py#L169-L192:

```
def find_executable(executable, path=None):
    """Tries to find 'executable' in the directories listed in 'path'.
    A string listing directories separated by 'os.pathsep'; defaults to
    os.environ['PATH'].  Returns the complete filename or None if not found.
    """
    if path is None:
        path = os.environ['PATH']

    paths = path.split(os.pathsep)
    base, ext = os.path.splitext(executable)

    if (sys.platform == 'win32') and (ext != '.exe'):
        executable = executable + '.exe'

    if not os.path.isfile(executable):
        for p in paths:
            f = os.path.join(p, executable)
            if os.path.isfile(f):
                # the file exists, we have a shot at spawn working
                return f
        return None
    else:
        return executable
```

**Comment by jesseward** [comment]
hey @sixninetynine , I (will) have a PR pending that performs the logic (more or less) similar to the above.

The difference being that the calling plugin will specify a list of platform specific  locations. I had originally created a patch that supplied a dynamic look-up against common paths, but then stepped it out in order to force the plug-in author to be explicit with their binary location (must supply the full path).  The thought being we didn't want fossor attempting to be smart about the binaries it was running (potentially as root).

https://github.com/linkedin/fossor/pull/3 was logged for discussion or other recommendations.

**Comment by jesseward** [comment]
Closing issue. 

@scallister has merged PR https://github.com/linkedin/fossor/commit/e009a5b15ff367eab5230144cb916c7650aa4672
