### ISSUE TITLE
Consider to grab remote data for analysing remote systems

### ISSUE THREAD

**Issue by iranzo** [linkedin/fossor#9]
It was suggested to allow gathering data from remote hosts for checking

**Comment by jstoja** [comment]
Any details on the feature? Would it be a client/server scenario, a file export, ... ?

**Comment by iranzo** [comment]
I think that client/server will make it harder unless the way is to run fossor on remote, output to file and 'master' fossor checks that file for the data via remote execution

**Comment by scallister** [comment]
For now I'd like to focus on having Fossor do local analysis well. Using a client/server model with Fossor would move away from the original goal.

That being said, I do think there is a lot of value in leveraging other remote execution platforms (IE Salt), ssh for loops...etc to accomplish this. Internally we have Fossor run against hosts when alerts fire and that has been helpful.
